# Generated by Django 5.0.6 on 2024-05-24 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answer_questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='Fach',
        ),
    ]
