# Generated by Django 5.0.4 on 2024-05-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer_questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
