# Generated by Django 5.0.6 on 2024-05-24 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer_questions', '0002_remove_exercise_fach'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='Fach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='answer_questions.fach'),
        ),
    ]
