# Generated by Django 5.0.6 on 2024-05-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer_questions', '0002_question_question_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='Exercise_Type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='Fach',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='Thema',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='klasse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
