# Generated by Django 5.0.6 on 2024-05-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer_questions', '0003_exercise_fach'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Fach', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='Fach',
        ),
        migrations.DeleteModel(
            name='Fach',
        ),
    ]
