# Generated by Django 5.0.6 on 2024-05-24 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer_questions', '0004_exercise_type_thema_remove_exercise_fach_delete_fach'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='exercise',
            name='Exercise_Type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises_type', to='answer_questions.exercise_type'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='Fach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises_fach', to='answer_questions.fach'),
        ),
        migrations.AlterField(
            model_name='thema',
            name='Fach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thema_fach', to='answer_questions.fach'),
        ),
    ]
