# Generated by Django 5.0.6 on 2024-05-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer_questions', '0006_alter_exercise_thema'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='head',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
