# Generated by Django 5.0.6 on 2024-05-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer_questions', '0007_exercise_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user_anwer',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
