# Generated by Django 5.0.6 on 2024-10-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer_questions', '0009_exercise_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='last_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='next_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
