# Generated by Django 5.0.4 on 2024-04-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fill_the_gaps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gapWord', models.IntegerField()),
                ('sentence', models.TextField()),
            ],
        ),
    ]
