# Generated by Django 5.0.4 on 2024-05-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fill_the_gaps', '0002_gaps'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AddField(
            model_name='gaps',
            name='category',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
