# Generated by Django 5.0.4 on 2024-05-08 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fill_the_gaps', '0003_delete_review_gaps_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gaps',
            name='category',
        ),
    ]
