# Generated by Django 5.0.4 on 2024-05-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fill_the_gaps', '0004_remove_gaps_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaps',
            name='category',
            field=models.CharField(default='default_value', max_length=100),
        ),
    ]
