# Generated by Django 5.0.4 on 2024-05-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fill_the_gaps', '0005_gaps_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaps',
            name='category',
            field=models.CharField(default='default_value', max_length=100, null=True),
        ),
    ]
